fix(ci): fix bugs introduced in the CI pipeline (#218)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,7 +15,7 @@ jobs:
   ci:
     runs-on: ubuntu-latest
     env:
-      LANGFUSE_HOST: "http://127.0.0.1:3000"
+      LANGFUSE_HOST: "http://localhost:3000"
       LANGFUSE_PUBLIC_KEY: "pk-lf-1234567890"
       LANGFUSE_SECRET_KEY: "sk-lf-1234567890"
       OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
@@ -58,14 +58,36 @@ jobs:
           TELEMETRY_ENABLED=false docker-compose up -d
           echo "::endgroup::"
 
+          sleep 20
+
           echo "::group::Install dependencies (necessary to run seeder)"
           npm ci
           echo "::endgroup::"
 
-          echo "::group::Apply migrations and seed db"
+          echo "::group::Seed db"
           cp .env.dev.example .env
-          npx --yes prisma migrate reset --force --skip-generate
+          npx --yes prisma db seed
           echo "::endgroup::"
+
+      # Add this step to check the health of the container
+      - name: Health check for langfuse server
+        run: |
+          echo "Checking if the langfuse server is up..."
+          retry_count=0
+          max_retries=5
+          until curl --output /dev/null --silent --head --fail http://localhost:3000/api/public/health
+          do
+            retry_count=`expr $retry_count + 1`
+            echo "Attempt $retry_count of $max_retries..."
+            if [ $retry_count -ge $max_retries ]; then
+              echo "Langfuse server did not respond in time. Printing logs..."
+              docker logs langfuse-server_langfuse-server_1
+              echo "Failing the step..."
+              exit 1
+            fi
+            sleep 5
+          done
+          echo "Langfuse server is up and running!"
 
       - name: Install Python
         uses: actions/setup-python@v4
