health

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -68,18 +68,22 @@ jobs:
           echo "::endgroup::"
 
       # Add this step to check the health of the container
-      - name: Check Health of Langfuse Server
+      - name: Health check for langfuse server
         run: |
-          echo "Checking health of Langfuse server..."
-          for i in {1..10}; do
-            if curl -f http://localhost:3000/api/public/health; then
-              echo "Langfuse server is up and running."
-              break
-            else
-              echo "Waiting for Langfuse server to be up..."
-              sleep 5
+          echo "Checking if the langfuse server is up..."
+          retry_count=0
+          max_retries=5
+          until curl --output /dev/null --silent --head --fail http://localhost:3000/api/public/health
+          do
+            retry_count=`expr $retry_count + 1`
+            echo "Attempt $retry_count of $max_retries..."
+            if [ $retry_count -ge $max_retries ]; then
+              echo "Langfuse server did not respond in time. Failing..."
+              exit 1
             fi
+            sleep 5
           done
+          echo "Langfuse server is up and running!"
 
       - name: Install Python
         uses: actions/setup-python@v4
